[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:web]
directory=/app
command=streamlit run streamlit_app.py --server.port=8080 --server.address=0.0.0.0
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:weibo_rss_turso_worker]
directory=/app
command=python3 -u weibo_rss_turso_worker.py --active-hours "%(ENV_WORKER_ACTIVE_HOURS)s" --verbose --interval-seconds %(ENV_WORKER_INTERVAL_SECONDS)s --worker-threads 30
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
