from __future__ import annotations

from .alias_task_repo import (
    ALIAS_TASK_AUTO_CONFIRM_CONFIDENCE_THRESHOLD,
    ALIAS_TASK_AUTO_CONFIRM_SOURCE,
    ALIAS_TASK_STATUS_BLOCKED,
    ALIAS_TASK_STATUS_MANUAL,
    ALIAS_TASK_STATUS_PENDING,
    ALIAS_TASK_STATUS_RESOLVED,
    AliasResolveTaskInfo,
    auto_confirm_alias_resolve_task_if_needed,
    cleanup_known_pending_alias_resolve_tasks,
    get_alias_resolve_task_status_summary,
    get_alias_resolve_tasks_map,
    increment_alias_resolve_attempts,
    list_manual_alias_resolve_tasks,
    list_pending_alias_resolve_tasks,
    set_alias_resolve_task_status,
    should_auto_confirm_alias_resolve_task,
)
from .alias_ai_runner import (
    AI_VALIDATION_MARKETS,
    AliasAiBatchSummary,
    AliasAiRoundSummary,
    DEFAULT_ALIAS_AI_BATCH_SIZE,
    apply_alias_ai_validation,
    enrich_alias_task_rows_with_ai,
    run_alias_manual_ai_rows,
    run_alias_manual_pending_round,
    stock_key_from_ai_stock_code,
    stock_market_from_key,
)
from .candidate_repo import (
    AUTO_ACCEPT_CONFIDENCE_THRESHOLD,
    AUTO_ACCEPT_SOURCE,
    StockAliasStatusSummary,
    accept_relation_candidate,
    auto_accept_relation_candidate_if_needed,
    block_relation_candidate,
    get_stock_alias_status_summary,
    ignore_relation_candidate,
    list_candidate_status_map,
    list_pending_candidates,
    list_pending_candidates_for_left_key,
    should_auto_accept_relation_candidate_row,
    upsert_relation_candidate,
)
from .relation_repo import (
    RELATION_LABEL_ALIAS,
    RELATION_LABEL_SAME_COMPANY,
    RELATION_TYPE_STOCK_ALIAS,
    RELATION_TYPE_STOCK_SIBLING,
    RELATION_TYPE_STOCK_SECTOR,
    get_confirmed_stock_alias_targets,
    list_stock_sibling_keys,
    record_stock_alias_relation,
    record_stock_sibling_relation,
    record_stock_sector_relation,
    sync_stock_sibling_relations_from_security_master,
)
from .security_master_repo import (
    get_official_names_by_stock_keys,
    get_stock_keys_by_official_names,
    upsert_security_master_stock,
)
from .shadow_dict_repo import rebuild_stock_dict_shadow_best_effort
from .schema import (
    RESEARCH_ALIAS_RESOLVE_TASKS_TABLE,
    RESEARCH_RELATION_CANDIDATES_TABLE,
    RESEARCH_RELATIONS_TABLE,
    RESEARCH_SECURITY_MASTER_TABLE,
)
from .service import get_research_workbench_engine_from_env


__all__ = [
    "ALIAS_TASK_AUTO_CONFIRM_CONFIDENCE_THRESHOLD",
    "ALIAS_TASK_AUTO_CONFIRM_SOURCE",
    "ALIAS_TASK_STATUS_BLOCKED",
    "ALIAS_TASK_STATUS_MANUAL",
    "ALIAS_TASK_STATUS_PENDING",
    "ALIAS_TASK_STATUS_RESOLVED",
    "AI_VALIDATION_MARKETS",
    "AliasResolveTaskInfo",
    "AliasAiBatchSummary",
    "AliasAiRoundSummary",
    "AUTO_ACCEPT_CONFIDENCE_THRESHOLD",
    "AUTO_ACCEPT_SOURCE",
    "DEFAULT_ALIAS_AI_BATCH_SIZE",
    "RESEARCH_ALIAS_RESOLVE_TASKS_TABLE",
    "RESEARCH_RELATION_CANDIDATES_TABLE",
    "RESEARCH_RELATIONS_TABLE",
    "RESEARCH_SECURITY_MASTER_TABLE",
    "RELATION_LABEL_ALIAS",
    "RELATION_LABEL_SAME_COMPANY",
    "RELATION_TYPE_STOCK_ALIAS",
    "RELATION_TYPE_STOCK_SIBLING",
    "RELATION_TYPE_STOCK_SECTOR",
    "StockAliasStatusSummary",
    "accept_relation_candidate",
    "auto_accept_relation_candidate_if_needed",
    "auto_confirm_alias_resolve_task_if_needed",
    "apply_alias_ai_validation",
    "block_relation_candidate",
    "cleanup_known_pending_alias_resolve_tasks",
    "enrich_alias_task_rows_with_ai",
    "get_confirmed_stock_alias_targets",
    "get_official_names_by_stock_keys",
    "get_alias_resolve_task_status_summary",
    "get_stock_alias_status_summary",
    "get_stock_keys_by_official_names",
    "get_alias_resolve_tasks_map",
    "get_research_workbench_engine_from_env",
    "ignore_relation_candidate",
    "increment_alias_resolve_attempts",
    "list_candidate_status_map",
    "list_manual_alias_resolve_tasks",
    "list_pending_alias_resolve_tasks",
    "list_pending_candidates",
    "list_pending_candidates_for_left_key",
    "list_stock_sibling_keys",
    "record_stock_alias_relation",
    "record_stock_sibling_relation",
    "record_stock_sector_relation",
    "rebuild_stock_dict_shadow_best_effort",
    "run_alias_manual_ai_rows",
    "run_alias_manual_pending_round",
    "set_alias_resolve_task_status",
    "should_auto_accept_relation_candidate_row",
    "should_auto_confirm_alias_resolve_task",
    "stock_key_from_ai_stock_code",
    "stock_market_from_key",
    "sync_stock_sibling_relations_from_security_master",
    "upsert_security_master_stock",
    "upsert_relation_candidate",
]
