from __future__ import annotations


TURSO_READY_RETRY_SECONDS = 5.0
BACKFILL_CACHE_FALLBACK_INTERVAL_SECONDS = 1800.0
SPOOL_FLUSH_MAX_ITEMS_PER_RUN = 200
SPOOL_FLUSH_RETRY_INTERVAL_SECONDS = 1.0
REDIS_AI_DUE_MAINTENANCE_MAX_ITEMS = 200
REDIS_AI_REQUEUE_MAX_ITEMS = 200
MAINTENANCE_RECOVERY_INTERVAL_CYCLES = 6
DUE_AI_CHECK_CACHE_TTL_SECONDS = 30.0
WORKER_TICK_HEARTBEAT_INTERVAL_SECONDS = 30.0


__all__ = [
    "BACKFILL_CACHE_FALLBACK_INTERVAL_SECONDS",
    "DUE_AI_CHECK_CACHE_TTL_SECONDS",
    "MAINTENANCE_RECOVERY_INTERVAL_CYCLES",
    "REDIS_AI_DUE_MAINTENANCE_MAX_ITEMS",
    "REDIS_AI_REQUEUE_MAX_ITEMS",
    "SPOOL_FLUSH_MAX_ITEMS_PER_RUN",
    "SPOOL_FLUSH_RETRY_INTERVAL_SECONDS",
    "TURSO_READY_RETRY_SECONDS",
    "WORKER_TICK_HEARTBEAT_INTERVAL_SECONDS",
]
