"""Shared constants (env names, defaults)."""

from alphavault.domains.common.time_format import DATETIME_FMT as _DATETIME_FMT

DATETIME_FMT = _DATETIME_FMT

# Platform names.
PLATFORM_WEIBO = "weibo"
PLATFORM_XUEQIU = "xueqiu"

# Env var names (keep centralized to avoid typos).
ENV_SPOOL_DIR = "SPOOL_DIR"
DEFAULT_SPOOL_DIR = "/tmp/alphavault-spool"

ENV_TURSO_MAX_CONNECTIONS = "TURSO_MAX_CONNECTIONS"
ENV_STANDARD_TURSO_DATABASE_URL = "STANDARD_TURSO_DATABASE_URL"
ENV_STANDARD_TURSO_AUTH_TOKEN = "STANDARD_TURSO_AUTH_TOKEN"
ENV_WEIBO_TURSO_DATABASE_URL = "WEIBO_TURSO_DATABASE_URL"
ENV_WEIBO_TURSO_AUTH_TOKEN = "WEIBO_TURSO_AUTH_TOKEN"
ENV_XUEQIU_TURSO_DATABASE_URL = "XUEQIU_TURSO_DATABASE_URL"
ENV_XUEQIU_TURSO_AUTH_TOKEN = "XUEQIU_TURSO_AUTH_TOKEN"

ENV_REDIS_URL = "REDIS_URL"
ENV_REDIS_QUEUE_KEY = "REDIS_QUEUE_KEY"
ENV_REDIS_DEDUP_TTL_SECONDS = "REDIS_DEDUP_TTL_SECONDS"
ENV_REDIS_AI_QUEUE_MAXLEN = "REDIS_AI_QUEUE_MAXLEN"
DEFAULT_REDIS_DEDUP_TTL_SECONDS = 7 * 24 * 3600
DEFAULT_REDIS_AI_QUEUE_MAXLEN = 20_000

# RSS
ENV_RSS_ACTIVE_HOURS = "RSS_ACTIVE_HOURS"
ENV_RSS_INTERVAL_SECONDS = "RSS_INTERVAL_SECONDS"
ENV_RSS_TIMEOUT_SECONDS = "RSS_TIMEOUT_SECONDS"
ENV_RSS_RETRIES = "RSS_RETRIES"
ENV_RSS_FEED_SLEEP_SECONDS = "RSS_FEED_SLEEP_SECONDS"
ENV_RSS_MANUAL_TRIGGER_KEY = "RSS_MANUAL_TRIGGER_KEY"
DEFAULT_RSS_TIMEOUT_SECONDS = 60.0
DEFAULT_RSS_RETRIES = 5
DEFAULT_RSS_FEED_SLEEP_SECONDS = 10.0
ENV_WEIBO_RSS_URLS = "WEIBO_RSS_URLS"
ENV_WEIBO_RSS_URL = "WEIBO_RSS_URL"
ENV_XUEQIU_RSS_URLS = "XUEQIU_RSS_URLS"
ENV_XUEQIU_RSS_URL = "XUEQIU_RSS_URL"
ENV_WEIBO_AUTHOR = "WEIBO_AUTHOR"
ENV_WEIBO_USER_ID = "WEIBO_USER_ID"
ENV_XUEQIU_AUTHOR = "XUEQIU_AUTHOR"
ENV_XUEQIU_USER_ID = "XUEQIU_USER_ID"

# Worker schedule (loop)
ENV_WORKER_ACTIVE_HOURS = "WORKER_ACTIVE_HOURS"
ENV_WORKER_INTERVAL_SECONDS = "WORKER_INTERVAL_SECONDS"
ENV_WORKER_STOCK_HOT_CACHE_INTERVAL_SECONDS = "WORKER_STOCK_HOT_CACHE_INTERVAL_SECONDS"

# AI
ENV_AI_API_KEY = "AI_API_KEY"
ENV_AI_MODEL = "AI_MODEL"
ENV_AI_BASE_URL = "AI_BASE_URL"
ENV_AI_API_MODE = "AI_API_MODE"
ENV_AI_PROMPT_VERSION = "AI_PROMPT_VERSION"
ENV_AI_STREAM = "AI_STREAM"
ENV_AI_TIMEOUT_SEC = "AI_TIMEOUT_SEC"
ENV_AI_TEMPERATURE = "AI_TEMPERATURE"
ENV_AI_RETRIES = "AI_RETRIES"
ENV_AI_RPM = "AI_RPM"
ENV_AI_MAX_INFLIGHT = "AI_MAX_INFLIGHT"
ENV_AI_TRACE_OUT = "AI_TRACE_OUT"
ENV_AI_REASONING_EFFORT = "AI_REASONING_EFFORT"
