"""Shared constants (env names, defaults)."""

from alphavault.domains.common.time_format import DATETIME_FMT as _DATETIME_FMT

DATETIME_FMT = _DATETIME_FMT

# Platform names.
PLATFORM_WEIBO = "weibo"
PLATFORM_XUEQIU = "xueqiu"
SCHEMA_WEIBO = "weibo"
SCHEMA_XUEQIU = "xueqiu"
SCHEMA_STANDARD = "standard"

# Env var names (keep centralized to avoid typos).
ENV_SPOOL_DIR = "SPOOL_DIR"
DEFAULT_SPOOL_DIR = "/tmp/alphavault-spool"
ENV_ALPHAVAULT_LOG_LEVEL = "ALPHAVAULT_LOG_LEVEL"
DEFAULT_ALPHAVAULT_LOG_LEVEL = "INFO"
ENV_NTFY_URL = "NTFY_URL"
ENV_NTFY_TOPIC = "NTFY_TOPIC"
ENV_NTFY_TOKEN = "NTFY_TOKEN"
ENV_NTFY_ALERT_DEDUP_WINDOW_SECONDS = "NTFY_ALERT_DEDUP_WINDOW_SECONDS"
ENV_NTFY_ALERT_TIMEOUT_SECONDS = "NTFY_ALERT_TIMEOUT_SECONDS"
ENV_RSS_NTFY_RULES_JSON = "RSS_NTFY_RULES_JSON"
DEFAULT_NTFY_URL = "https://ntfy.sh"
DEFAULT_NTFY_ALERT_DEDUP_WINDOW_SECONDS = 15 * 60
DEFAULT_NTFY_ALERT_TIMEOUT_SECONDS = 10.0
DEFAULT_RSS_NTFY_NOTIFY_TIMEOUT_SECONDS = 10.0
DEFAULT_RSS_NTFY_SENT_TTL_SECONDS = 30 * 24 * 3600

ENV_STARTUP_HEALTHCHECK_SCHEMA_TARGET = "STARTUP_HEALTHCHECK_SCHEMA_TARGET"
ENV_POSTGRES_DSN = "POSTGRES_DSN"
ENV_POSTGRES_POOL_MAX_SIZE = "POSTGRES_POOL_MAX_SIZE"
ENV_CLOUDFLARE_ACCESS_TEAM_DOMAIN = "CLOUDFLARE_ACCESS_TEAM_DOMAIN"
ENV_CLOUDFLARE_ACCESS_AUD = "CLOUDFLARE_ACCESS_AUD"

ENV_REDIS_URL = "REDIS_URL"
ENV_REDIS_QUEUE_KEY = "REDIS_QUEUE_KEY"
ENV_REDIS_DEDUP_TTL_SECONDS = "REDIS_DEDUP_TTL_SECONDS"
ENV_REDIS_AI_QUEUE_MAXLEN = "REDIS_AI_QUEUE_MAXLEN"
DEFAULT_REDIS_DEDUP_TTL_SECONDS = 7 * 24 * 3600
DEFAULT_REDIS_AI_QUEUE_MAXLEN = 20_000

# RSS
ENV_RSS_ACTIVE_HOURS = "RSS_ACTIVE_HOURS"
ENV_RSS_INTERVAL_SECONDS = "RSS_INTERVAL_SECONDS"
ENV_RSS_TIMEOUT_SECONDS = "RSS_TIMEOUT_SECONDS"
ENV_RSS_RETRIES = "RSS_RETRIES"
ENV_RSS_FEED_SLEEP_SECONDS = "RSS_FEED_SLEEP_SECONDS"
ENV_WORKER_ADMIN_TRIGGER_KEY = "WORKER_ADMIN_TRIGGER_KEY"
DEFAULT_RSS_TIMEOUT_SECONDS = 60.0
DEFAULT_RSS_RETRIES = 5
DEFAULT_RSS_FEED_SLEEP_SECONDS = 10.0
ENV_WEIBO_RSS_URLS = "WEIBO_RSS_URLS"
ENV_WEIBO_RSS_URL = "WEIBO_RSS_URL"
ENV_XUEQIU_RSS_URLS = "XUEQIU_RSS_URLS"
ENV_XUEQIU_RSS_URL = "XUEQIU_RSS_URL"
ENV_WEIBO_AUTHOR = "WEIBO_AUTHOR"
ENV_WEIBO_USER_ID = "WEIBO_USER_ID"
ENV_XUEQIU_AUTHOR = "XUEQIU_AUTHOR"
ENV_XUEQIU_USER_ID = "XUEQIU_USER_ID"

# Worker schedule (loop)
ENV_WORKER_ACTIVE_HOURS = "WORKER_ACTIVE_HOURS"
ENV_WORKER_INTERVAL_SECONDS = "WORKER_INTERVAL_SECONDS"

# AI
ENV_AI_API_KEY = "AI_API_KEY"
ENV_AI_MODEL = "AI_MODEL"
ENV_AI_BASE_URL = "AI_BASE_URL"
ENV_AI_API_MODE = "AI_API_MODE"
ENV_AI_PROMPT_VERSION = "AI_PROMPT_VERSION"
ENV_AI_STREAM = "AI_STREAM"
ENV_AI_TIMEOUT_SEC = "AI_TIMEOUT_SEC"
ENV_AI_TEMPERATURE = "AI_TEMPERATURE"
ENV_AI_RETRIES = "AI_RETRIES"
ENV_AI_RPM = "AI_RPM"
ENV_AI_MAX_INFLIGHT = "AI_MAX_INFLIGHT"
ENV_AI_TRACE_OUT = "AI_TRACE_OUT"
ENV_AI_REASONING_EFFORT = "AI_REASONING_EFFORT"
ENV_AI_QUEUE_ACK_TIMEOUT_SEC = "AI_QUEUE_ACK_TIMEOUT_SEC"
ENV_AI_TASK_PROFILE_PREFIX = "AI_TASK_"
ENV_AI_PROFILE_PREFIX = "AI_PROFILE_"
ENV_AI_LIMIT_GROUP_PREFIX = "AI_LIMIT_GROUP_"
DEFAULT_AI_PROFILE_NAME = "default"
DEFAULT_AI_LIMIT_GROUP_NAME = "default"
DEFAULT_AI_RPM = 12.0
DEFAULT_AI_MAX_INFLIGHT = 12

# Embedding
ENV_EMBEDDING_API_KEY = "EMBEDDING_API_KEY"
ENV_EMBEDDING_MODEL = "EMBEDDING_MODEL"
ENV_EMBEDDING_DIMENSIONS = "EMBEDDING_DIMENSIONS"
ENV_EMBEDDING_BASE_URL = "EMBEDDING_BASE_URL"
ENV_EMBEDDING_TIMEOUT_SEC = "EMBEDDING_TIMEOUT_SEC"
ENV_EMBEDDING_RETRIES = "EMBEDDING_RETRIES"
ENV_EMBEDDING_RPM = "EMBEDDING_RPM"
ENV_EMBEDDING_MAX_INFLIGHT = "EMBEDDING_MAX_INFLIGHT"
ENV_EMBEDDING_BATCH_SIZE = "EMBEDDING_BATCH_SIZE"
ENV_EMBEDDING_TASK_PROFILE_PREFIX = "EMBEDDING_TASK_"
ENV_EMBEDDING_PROFILE_PREFIX = "EMBEDDING_PROFILE_"
ENV_EMBEDDING_LIMIT_GROUP_PREFIX = "EMBEDDING_LIMIT_GROUP_"
DEFAULT_EMBEDDING_PROFILE_NAME = "default"
DEFAULT_EMBEDDING_LIMIT_GROUP_NAME = "default"
DEFAULT_EMBEDDING_MODEL = "Qwen/Qwen3-Embedding-8B"
DEFAULT_EMBEDDING_TIMEOUT_SECONDS = 60.0
DEFAULT_EMBEDDING_RETRIES = 5
DEFAULT_EMBEDDING_RPM = 120.0
DEFAULT_EMBEDDING_MAX_INFLIGHT = 8
DEFAULT_EMBEDDING_BATCH_SIZE = 32
DEFAULT_SEMANTIC_DOC_EMBEDDING_DIMENSIONS = 2048

# Reranker
ENV_RERANKER_API_KEY = "RERANKER_API_KEY"
ENV_RERANKER_MODEL = "RERANKER_MODEL"
ENV_RERANKER_BASE_URL = "RERANKER_BASE_URL"
ENV_RERANKER_TIMEOUT_SEC = "RERANKER_TIMEOUT_SEC"
ENV_RERANKER_RETRIES = "RERANKER_RETRIES"
ENV_RERANKER_RPM = "RERANKER_RPM"
ENV_RERANKER_MAX_INFLIGHT = "RERANKER_MAX_INFLIGHT"
ENV_RERANKER_TOP_N = "RERANKER_TOP_N"
ENV_RERANKER_TASK_PROFILE_PREFIX = "RERANKER_TASK_"
ENV_RERANKER_PROFILE_PREFIX = "RERANKER_PROFILE_"
ENV_RERANKER_LIMIT_GROUP_PREFIX = "RERANKER_LIMIT_GROUP_"
DEFAULT_RERANKER_PROFILE_NAME = "default"
DEFAULT_RERANKER_LIMIT_GROUP_NAME = "default"
DEFAULT_RERANKER_MODEL = "Qwen/Qwen3-Reranker-8B"
DEFAULT_RERANKER_TIMEOUT_SECONDS = 60.0
DEFAULT_RERANKER_RETRIES = 3
DEFAULT_RERANKER_RPM = 60.0
DEFAULT_RERANKER_MAX_INFLIGHT = 4
DEFAULT_RERANKER_TOP_N = 20
